export { NETWORK_PORT_MAXIMAL_VALUE } from "./ComputerNetworking/NETWORK_PORT_MAXIMAL_VALUE";
export { NETWORK_PORT_MINIMAL_VALUE } from "./ComputerNetworking/NETWORK_PORT_MINIMAL_VALUE";

export { HOURS_PER_STELLAR_DAY } from "./DateTime/HOURS_PER_STELLAR_DAY";
export { MAXIMAL_DAYS_IN_MONTH } from "./DateTime/MAXIMAL_DAYS_IN_MONTH";

export { MINIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS } from "./EmailAddress/MINIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS";
