export { HTTP_DEFAULT_PORT } from "./ComputerNetworking/HTTP_DEFAULT_PORT";
export { HTTPS_DEFAULT_PORT } from "./ComputerNetworking/HTTPS_DEFAULT_PORT";
export { NETWORK_PORT_MAXIMAL_VALUE } from "./ComputerNetworking/NETWORK_PORT_MAXIMAL_VALUE";
export { NETWORK_PORT_MINIMAL_VALUE } from "./ComputerNetworking/NETWORK_PORT_MINIMAL_VALUE";


export { DAYS_COUNT_IN_WEEK } from "./DateTime/DAYS_COUNT_IN_WEEK";
export { DaysOfWeekNames } from "./DateTime/DaysOfWeekNames";
export { HOURS_COUNT_IN_STELLAR_DAY } from "./DateTime/HOURS_COUNT_IN_STELLAR_DAY";
export { MAXIMAL_DAYS_IN_MONTH } from "./DateTime/MAXIMAL_DAYS_IN_MONTH";
export { MAXIMAL_SUPPORTED_UNIX_MILLISECONDS_AMOUNT } from "./DateTime/MAXIMAL_SUPPORTED_UNIX_MILLISECONDS_AMOUNT";
export { MINIMAL_SUPPORTED_UNIX_MILLISECONDS_AMOUNT } from "./DateTime/MINIMAL_SUPPORTED_UNIX_MILLISECONDS_AMOUNT";
export { MINUTES_COUNT_IN_HOUR } from "./DateTime/MINUTES_COUNT_IN_HOUR";
export { MONTHS_COUNT_IN_YEAR } from "./DateTime/MONTHS_COUNT_IN_YEAR";
export { MonthsNames } from "./DateTime/MonthsNames";
export { SECONDS_COUNT_IN_MINUTE } from "./DateTime/SECONDS_COUNT_IN_MINUTE";

export { CHARACTERS_COUNT_IN_DATE_PART_OF_ISO8601_STRING } from
    "./DateTime/ISO8601/CHARACTERS_COUNT_IN_DATE_PART_OF_ISO8601_STRING";
export { CHARACTERS_COUNT_IN_FULL_ISO8601_STRING } from "./DateTime/ISO8601/CHARACTERS_COUNT_IN_FULL_ISO8601_STRING";

export { EMAIL_ADDRESS_VALID_PATTERN } from "./EmailAddress/EMAIL_ADDRESS_VALID_PATTERN";
export { MAXIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS } from "./EmailAddress/MAXIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS";
export { MINIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS } from "./EmailAddress/MINIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS";
