

export { NETWORK_PORT_MAXIMAL_VALUE } from "./ComputerNetworking/NETWORK_PORT_MAXIMAL_VALUE";
export { NETWORK_PORT_MINIMAL_VALUE } from "./ComputerNetworking/NETWORK_PORT_MINIMAL_VALUE";

export { HOURS_PER_STELLAR_DAY } from "./DateTime/HOURS_PER_STELLAR_DAY";
export { MAXIMAL_DAYS_IN_MONTH } from "./DateTime/MAXIMAL_DAYS_IN_MONTH";
export { MINUTES_PER_HOUR } from "./DateTime/MINUTES_PER_HOUR";
export { SECONDS_PER_MINUTE } from "./DateTime/SECONDS_PER_MINUTE";

export { CHARACTERS_COUNT_IN_FULL_ISO8601_STRING } from "./DateTime/ISO8601/CHARACTERS_COUNT_IN_FULL_ISO8601_STRING";
export { CHARACTERS_COUNT_OF_DATE_PART_IN_ISO8601_STRING } from
    "./DateTime/ISO8601/CHARACTERS_COUNT_OF_DATE_PART_IN_ISO8601_STRING";

export { MINIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS } from "./EmailAddress/MINIMAL_CHARACTERS_COUNT_OF_EMAIL_ADDRESS";
